### ISSUE TITLE
What happened to `ToScriptHash`?

### ISSUE THREAD

**Issue by nickfujita** [ontio/ontology-python-compiler#37]
Why was `boa.builtins. ToScriptHash` not included in this version of the compiler, or what was it replaced with?

For example
```
# ONT Big endian Script Hash: 0x0100000000000000000000000000000000000000
OntContract = ToScriptHash("AFmseVrdL9f9oyCzZefL9tG6UbvhUMqNMV")
```

**Comment by carltraveler** [comment]
just replace ToScriptHash with Base58ToAddress.  these two method are same functino. so only leave one

**Comment by z0Yo** [comment]
@carltraveler was `Base58ToAddress` removed? The documentation says it is at `ontology.interop.System.Runtime`, but SmartX throws the compile error ` Function 'Base58ToAddress' do not defined or imported.`
