### ISSUE TITLE
The generated debug info seems wrong

### ISSUE THREAD

**Issue by hsiaosiyuan0** [ontio/ontology-python-compiler#38]
Reproducible steps:

1. Use VSCode Version 1.31.1 (1.31.1)
2. Use [vscode-ext-ontology](https://marketplace.visualstudio.com/items?itemName=zamborsky.vscode-ext-ontology) and config it to use Python Compiler version 2.0
3. Use this [test contract](https://github.com/punica-box/punica-init-default-box/blob/master/contracts/hello_ontology.py)
4. Compile that contract to generate debug info
5. Add breakpoint at line #82
6. Find the section named `SMART CONTRACT METHODS` on the left panel then double click the method `testHello`
7. Fill the params on the new invoking tab then click `Debug`
8. Click `step over` after the debug process is suspended at line #82
9. The wrong stack frame `testList` appears under the call stack section on the left panel, since we still under method `testHello`, the correct stack frame should be `testHello`.

Please take a quick view of below screenshot:

<img src="https://user-images.githubusercontent.com/22588905/54106715-fc53e480-4411-11e9-99d5-913c3599b1fc.gif" width="400" />

**Comment by carltraveler** [comment]
#42  have fixed the issue
