### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by WyattMufson** [ontio/ontology-python-compiler#64]
When compiling the [Ryu NFT contract](https://github.com/Ryucoin/RyuNFTs-ONT/blob/master/src/nfts.py) and running the `name` method I get the error:
```
Error: does not support the operation code
```

If I compile it with SmartX, it works. SmartX gives me the script hash `bd97b827693a1ab0aa2c61d647915851676daa8e` and the compiler locally gives me `08bb4246c8ef7c3891c46749b02d07ada3fdac07`.

**Comment by WyattMufson** [comment]
This happens on the test net, but works on a private net running the most recent version of Ontology.

**Comment by carltraveler** [comment]
did you use the lastest compiler to run the on ontology main net?  I think  you can check out the lastest tag

**Comment by WyattMufson** [comment]
So when running it with the latest version of the python compiler the script hash does not match the one with smartx version. When running it with the release version 1.1.0 it matches smartx.

Why does the newer build of the compiler give a different script hash?

**Comment by carltraveler** [comment]
because of different byte code generated

**Comment by WyattMufson** [comment]
Is it a problem that they have different byte code? Will that not effect the contract when being used?

**Comment by WyattMufson** [comment]
Would you recommend using the v1.1.0 compiler for releases to the mainnet?

**Comment by carltraveler** [comment]
yes.  that why I tag the v1. 1.0

**Comment by WyattMufson** [comment]
Great, thanks!
